export const constants = {
	GET_PRODUCTS: 'GET_PRODUCTS',
	GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
	GET_PRODUCTS_FAIL: 'GET_PRODUCTS_FAIL',
	ADD_PRODUCT_COMMENT: 'ADD_PRODUCT_COMMENT',
	REHYDRATE_COMMENTS: 'REHYDRATE_COMMENTS'
};
